Fix interpretations in mitotip_score_fixed_del.csv
KCCG/mity pull request #15
Opened 2022-03-23 16:21 UTC by anjalijain22

- Addresses issue #14 
- Changes have been made to two files:
1. **mitylib/annot/mitotip_score_fixed_del.csv:** The MitoTip_interpretations column values have been changed. The values can be `likely pathogenic`, `possibly pathogenic`, `likely benign` or `possibly benign` depending on the Mitotip_Percentile column value according to [this table](https://www.mitomap.org/MITOMAP/MitoTipInfo). Additionally, some variants have values "Confirmed pathogenic" according to the [list of confirmed pathogenic variants on MitoMap](https://mitomap.org/foswiki/bin/view/MITOMAP/MutationsRNACfrm).
2. **mitylib/report.py:** Updated documentation for "MitoTip_interpretation" to include Confirmed pathogenic variants.

- Known conflict:
1. Some variants having `Confirmed pathogenic` status in the MitoTip_interpretation column in mitylib/annot/mitotip_score_fixed_del.csv may have a `reported` value in the "status_mitomap" column of mitylib/annot/mitomap_panel_annotations.csv. 
2. Next step: Update mitylib/annot/mitomap_panel_annotations.csv file to the latest version

2022-03-24 06:19 UTC, drmjc commented on mitylib/report.py
> +        "Variants reported as Confirmed pathogenic have additional lines "
Confirmed Pathogenic in MITOMAP

2022-03-24 06:21 UTC, drmjc requested changes
thanks so much for the PR.
Can you please tweak the wording in report.py as noted, and version bump 'mitylib/_version.py' to 0.3.1

2022-03-24 15:47 UTC, anjalijain22 commented on mitylib/report.py
> +        "Variants reported as Confirmed pathogenic have additional lines "
Done!

2022-03-30 21:05 UTC, drmjc approved these changes

2022-03-30 21:06 UTC, drmjc commented
Thanks @anjalijain22.

@joecop can you please give me admin access again (and for clinsv)? thanks

2022-05-06 05:54 UTC, merged